<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-78J31B7" failures="1" tests="3" name="Android" time="88.356" errors="0" timestamp="2023-10-10T10:37:05 GST">
  <testcase classname="com.qa.tests.LoginTests" name="invalidUsername" time="13.117">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fffdfff]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fffdfff]
at com.qa.tests.LoginTests.invalidUsername(LoginTests.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- invalidUsername -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserPassword" time="12.446"/>
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="13.002"/>
</testsuite> <!-- Android -->
